project_name: prometheus-libvirt-exporter
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: prometheus-libvirt-exporter
    dir: .
    main: ./main.go
    binary: prometheus-libvirt-exporter
    flags:
      - -tags=netgo
      - -v
      - -a
    ldflags:
      - -w -s
      - -X main.version={{ .Version }} -X main.commit={{ .Commit }}
    goos:
      - darwin
      - freebsd
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: riscv64

dockers:
  - ids:
      - prometheus-libvirt-exporter
    image_templates:
      - ghcr.io/inovex/{{ .ProjectName }}:{{ .Version }}-amd64
    goos: linux
    goarch: amd64
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
      - "--build-arg=BINARY_NAME={{ .ProjectName }}"
      - "--platform=linux/amd64"
    use: buildx
  - ids:
      - prometheus-libvirt-exporter
    image_templates:
      - ghcr.io/inovex/{{ .ProjectName }}:{{ .Version }}-arm64
    goos: linux
    goarch: arm64
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
      - "--build-arg=BINARY_NAME={{ .ProjectName }}"
      - "--platform=linux/arm64"
    use: buildx
  - ids:
      - prometheus-libvirt-exporter
    image_templates:
      - ghcr.io/inovex/{{ .ProjectName }}:{{ .Version }}-riscv64
    goos: linux
    goarch: riscv64
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
      - "--build-arg=BINARY_NAME={{ .ProjectName }}"
      - "--platform=linux/riscv64"
    use: buildx

docker_manifests:
- name_template: 'ghcr.io/inovex/{{ .ProjectName }}:{{ .Version }}'
  image_templates:
  - 'ghcr.io/inovex/{{ .ProjectName }}:{{ .Version }}-amd64'
  - 'ghcr.io/inovex/{{ .ProjectName }}:{{ .Version }}-arm64'
  - 'ghcr.io/inovex/{{ .ProjectName }}:{{ .Version }}-riscv64'

#Configuration for building packages for apk, deb and rpm package managers
nfpms:
  - id: "prometheus-libvirt-exporter"
    package_name: "prometheus-libvirt-exporter"
    file_name_template: prometheus-libvirt-exporter-{{ .Version }}.{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}
    builds:
      - prometheus-libvirt-exporter
    maintainer: "inovex"
    description: |
      Prometheus-libvirt-exporter service (host and vm metrics exposed for prometheus, written in Go with pluggable metric collectors)
    homepage: "https://github.com/inovex/prometheus-libvirt-exporter"
    license: "MIT License"
    formats:
      - deb
      - rpm
    bindir: "/usr/bin"
    priority: optional
    contents:
      - src: contrib/prometheus-libvirt-exporter.service
        dst: /etc/systemd/system/prometheus-libvirt-exporter.service

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    format: tar.gz
    wrap_in_directory: true

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}_checksums.txt"
  algorithm: sha256

# Configuration for GitHub Releases
release:
  github:
    owner: inovex
    name: prometheus-libvirt-exporter
  footer: |
    ## Docker Images
    - ghcr.io/inovex/prometheus-libvirt-exporter:{{ trimprefix .Tag "v" }} (universal, multi-platform)
    - ghcr.io/inovex/prometheus-libvirt-exporter:{{ trimprefix .Tag "v" }}-amd64
    - ghcr.io/inovex/prometheus-libvirt-exporter:{{ trimprefix .Tag "v" }}-arm64
    - ghcr.io/inovex/prometheus-libvirt-exporter:{{ trimprefix .Tag "v" }}-riscv64
  prerelease: auto
  replace_existing_draft: true
