name: Lint Go Code
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
    - name: Lint
      uses: golangci/golangci-lint-action@v6.1.1
      with:
          version: v1.57.2
